import Navbar from "./Navbar";
import type { Metadata } from "next";
import { Be_Vietnam_Pro, Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-display",
});

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  variable: "--font-body",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className={`${beVietnamPro.variable} ${inter.variable} min-h-full flex flex-col font-body`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
